### ISSUE TITLE
Add ESP32 support

### ISSUE THREAD

**Issue by yarons** [w84death/smolOS#3]
As the title implies, ESP32-S3 is a very popular chip powered by Xtensa LX7 as opposed to the C variant of ESP32 (such as ESP32-C3 and ESP32-C6) powered by RISC-V processors.

So since the S3 variant is pretty similar to ESP8266 it should be relatively easy to port it (with the exception of dual core and being 32 bit) while the C variant is a different story and might be more complex.

Thank you for this awesome project!

**Comment by jakobi** [comment]
Just to mention that micropython ports include the ESP32-C2 and later now:

https://micropython.org/download/esp32c3/, though drilling down on micropython.org I still do not see much mention in e.g. the esp32 section. 

Circuitpython also seems to have gained a port since I last checked a few months ago.

Wrt dual core: all ESP32-S2 and a very few ESP32 (solo-1, to my surprise) are single core; ESP-S3 returned to the usually dual-core nature of the ESP32.  C2/C3 (and C6; and H2?) are single core again, and part of Espressif's move to RISC-V.
